### ISSUE TITLE
"04_INSERTFLIGHTS.SQL" and "06_INSERTBOOKINGS.SQL"  does not insert flights/bookings in my databases

### ISSUE THREAD

**Issue by amitkovski** [aprobinda/proj_ddb_suse17#8]
When I am executing this sql.file no querries are inserted in Flight/Booking table.

But due to the log file, no errors are visible. Everthing seems to be committed. 

LOG: Start <12:13:57.901> for "04_INSERTFLIGHTS.SQL"
        Start:<12:10:55.406> for "06_INSERTBOOKINGS.SQL"
[fedprot.txt](https://github.com/aprobinda/proj_ddb_suse17/files/1269950/fedprot.txt)

**Comment by MrImamBux** [comment]
Make sure other foreign keys parent data is available. For example to insert flights, airlines and airplanes should be there. If I run INSERTFLIGHTS.SQL, I also get exception on code level saying FS_NACH is violated and FS_NACH is the foreign key constraint for FLUGHHAFEN. @amitkovski

**Comment by aprobinda** [comment]
2.2.6.4 If no partitioning clause is given, the entire table hast to be stored on the “first” of your CDBSes (PINATUBO). This means that FLUGHAFEN, FLUGLINIE tables will only exist in Pinatubo DB.
    Table PASSAGIER is partitioned over three DBs but has no FOREIGN KEYS referencing to the tables above.
    Table BUCHUNG has the same partitioning over three DBs as the PASSAGIER table, has a FOREIGN KEY PNR that references to PASSAGIER, so no problem at this stage.
However, it has FOREIGN KEYS to FLUGHAFEN, FLUGLINIE, so all of the INSERT statements with PNR>35 will fail due to foreign keys unavailable.  Presisely, these foreign key constraints will be violated: FS_NACH and FS_VON referencing FLUGHAFEN,  FS_FLC referencing FLUGLINIE.
Same problem exists for FLUG table.
    The first naive solution is to change the rule 2.2.6.4, so all of the required parent tables will be created in every DB. Plus, for these parent tables the required FOREIGN keys tuples will  be INSERTed before inserting tuples into child table.

**Comment by MrImamBux** [comment]
Not producible on Professor's Application layer because the files are executed in sequence. Problem was faced because of inserting column in a records as a foreign key which is not available in their parent tables.
